vex_bookstore:
    resource: "@VexBookstoreBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: VexBookstoreBundle:Security:login }
login_check:
    pattern:   /login_check

logout:
    path:   /logout