VexDev\Bundle\BookstoreBundle\Entity\Book:
    type: entity
    table: book
    fields:
        isbn:
            id: true
            type: string
            length: 20
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        url:
            type: string
            length: 255
            fixed: false
            nullable: true
        imgurl:
            type: string
            length: 255
            fixed: false
            nullable: true
        price:
            type: decimal
            nullable: true
        pages:
            type: integer
            unsigned: false
            nullable: true
        edition:
            type: integer
            unsigned: false
            nullable: true
    manyToMany:
        aid:
            targetEntity: Author
            cascade: {  }
            mappedBy: isbn
            inversedBy: null
            joinTable: null
            orderBy: null
        cid:
            targetEntity: Category
            cascade: {  }
            mappedBy: isbn
            inversedBy: null
            joinTable: null
            orderBy: null
        eid:
            targetEntity: Editor
            cascade: {  }
            mappedBy: isbn
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
