VexDev\Bundle\BookstoreBundle\Entity\User:
    type: entity
    table: user
    fields:
        email:
            id: true
            type: string
            length: 255
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: true
        surname:
            type: string
            length: 100
            fixed: false
            nullable: true
        password:
            type: string
            length: 100
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
